name: release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: install rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - name: cache rust toolchain
        uses: Swatinem/rust-cache@v2

      - name: install musl-tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: cargo build
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cp target/x86_64-unknown-linux-musl/release/beacon beacon-linux-x86_64
          gh release delete --yes ${{ github.ref_name }} || true
          gh release create --generate-notes ${{ github.ref_name }} beacon-linux-x86_64
